server:
  port: 9411
# 最佳实践：springcloud应用都要指定application.name
spring:
  application:
    name: springcloud-zipkin-server
  main:
    allow-bean-definition-overriding: true
# 当bean重复定义时允许相同key情况下beanDefinition实例的覆盖

eureka:
  client:
    serviceUrl:
      #      指定服务注册中心的地址
      defaultZone: http://localhost:10080/eureka/
#      上面是eureka单机注册中心。下面是eureka集群模式
#      defaultZone: http://admin:123456@eureka2:8001/eureka/,http://admin:123456@eureka3:8002/eureka/,http://admin:123456@eureka2:8003/eureka/
management:
  metrics:
    web:
      server:
        auto-time-requests: false
zipkin:
  storage:
    StorageComponent: elasticsearch
    type: elasticsearch
    elasticsearch:
      hosts: 172.16.22.54:9201
      cluster: app
      index: zipkin
      index-shards: 5
      index-replicas: 1
#  zipkin.storage.StorageComponent=elasticsearch
#  zipkin.storage.type=elasticsearch
#  #可以做集群，我用的本地测试没有部署elastic集群
#  zipkin.storage.elasticsearch.hosts=192.168.42.40:9200
#  zipkin.storage.elasticsearch.cluster=elasticsearch
#  zipkin.storage.elasticsearch.index=zipkin
#  zipkin.storage.elasticsearch.index-shards=5
#  zipkin.storage.elasticsearch.index-replicas=1
#  maxHttpHeaderSize=8192
#  action.auto_create_index=true
